[package]
name = "cli-toolkit-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.107"
quote = "1.0.23"
convert_case = "0.6.0"

[lib]
proc-macro = true
